### ISSUE TITLE
Error running project

### ISSUE THREAD

**Issue by nifl** [geelen/typeslab#13]
I installed this project with no errors but when running in the browser, nothing is rendered to the page and in the console I receive the error:

```
Uncaught (in promise) Error: Cannot read property 'replace' of undefined
Error loading http://127.0.0.1:8081/styles/reset.amcss!http://127.0.0.1:8081/amcss.js as "./reset.amcss!" from http://127.0.0.1:8081/styles/index.js
at SystemJSLoader.fetch (http://127.0.0.1:8081/jspm_packages/github/geelen/plugin-postcss@master/index.js!transpiled:55:54)
at SystemJSLoader.<anonymous> (http://127.0.0.1:8081/jspm_packages/system.src.js:3519:49)
at SystemJSLoader.<anonymous> (http://127.0.0.1:8081/jspm_packages/system.src.js:3613:20)
at SystemJSLoader.fetch (http://127.0.0.1:8081/jspm_packages/system.src.js:3834:20)
at http://127.0.0.1:8081/jspm_packages/system.src.js:326:33
```

**Comment by apnerve** [comment]
+1

PS: I just installed it and haven't gone through the code. Will update here once I find something,
