### ISSUE TITLE
Error after fresh installation

### ISSUE THREAD

**Issue by FabienGregoire** [geelen/typeslab#14]
Hi,
Thanks you for your projet, it's very interesting.
But, after the installation (like say in Readme.md; I have just add the lock option on jspm install command), I have this issue on the Chrome's console :
`Uncaught (in promise) Error: Cannot read property 'replace' of undefined
    Error loading http://127.0.0.1:8080/styles/reset.amcss!http://127.0.0.1:8080/amcss.js as "./reset.amcss!" from http://127.0.0.1:8080/styles/index.js
    at SystemJSLoader.fetch (http://127.0.0.1:8080/jspm_packages/github/geelen/plugin-postcss@master/index.js!transpiled:57:54)
    at SystemJSLoader.<anonymous> (http://127.0.0.1:8080/jspm_packages/system.src.js:4320:49)
    at SystemJSLoader.fetch (http://127.0.0.1:8080/jspm_packages/system.src.js:4565:20)
    at http://127.0.0.1:8080/jspm_packages/system.src.js:326:33`

It seems appears because of the undefined pluginArgument attribut of medata (line 41 on src\jspm_packages\github\geelen\plugin-postcss@master\index.js).

Sorry, I'm a newbie in the world of npm... so maybe I'm do something wrong.
Thank you for your help

**Comment by michaelmior** [comment]
Getting the same error myself. This appears to be a duplicate of #13.
